import {API_BASE_URL} from '../config/api';
import {BEAR_FEED_IDS,BEAR_FEED_SPOT_IDS,FARM_REWARD_IDS,GARDEN_FLOWER_IDS,type BearFeedId,type BearFeedSpotId,type FarmRewardId,type GardenFlowerId,type PersonalFarmProgressDto} from '../../shared/personal-farm';
export const PERSONAL_FARM_PROGRESS_CHANGED='personal-farm-progress-changed';
type ApiErrorBody={error?:{code?:unknown;message?:unknown}}; type ApiSuccessBody={success?:unknown;data?:unknown};
const errorMessages:Record<string,string>={UNAUTHENTICATED:'\uB85C\uADF8\uC778\uC774 \uD544\uC694\uD569\uB2C8\uB2E4.',NETWORK_ERROR:'\uC11C\uBC84\uC5D0 \uC5F0\uACB0\uD560 \uC218 \uC5C6\uC2B5\uB2C8\uB2E4. \uC7A0\uC2DC \uD6C4 \uB2E4\uC2DC \uC2DC\uB3C4\uD574 \uC8FC\uC138\uC694.',FLOWER_ALREADY_COLLECTED:'\uC774\uBBF8 \uC218\uC9D1\uD55C \uAF43\uC785\uB2C8\uB2E4.',FLOWER_NOT_COLLECTED:'\uBA3C\uC800 \uC218\uBAA9\uC6D0\uC5D0\uC11C \uAF43\uC744 \uC218\uC9D1\uD574 \uC8FC\uC138\uC694.',FEED_NOT_COLLECTED:'\uC0AC\uC6A9\uD560 \uC218 \uC788\uB294 \uBA39\uC774\uAC00 \uC5C6\uC2B5\uB2C8\uB2E4.',FEED_SPOT_ALREADY_COMPLETED:'\uC774\uBBF8 \uC644\uB8CC\uD55C \uBA39\uC774 \uCCB4\uD5D8 \uC9C0\uC810\uC785\uB2C8\uB2E4.',FLOWER_ALREADY_PLANTED:'\uC774\uBBF8 \uC2EC\uC740 \uAF43\uC785\uB2C8\uB2E4.',FARM_LOCKED:'\uC218\uBAA9\uC6D0\uACFC \uBCA0\uC5B4\uD2B8\uB9AC\uD30C\uD06C \uBBF8\uC158\uC744 \uC644\uB8CC\uD558\uBA74 \uBCF4\uC0C1\uC774 \uC5F4\uB9BD\uB2C8\uB2E4.'};
export class PersonalFarmApiError extends Error{constructor(readonly code:string,message?:string,readonly status=0){super(errorMessages[code]??message??'\uAC1C\uC778 \uD31C \uC815\uBCF4\uB97C \uCC98\uB9AC\uD558\uC9C0 \uBABB\uD588\uC2B5\uB2C8\uB2E4. \uB2E4\uC2DC \uC2DC\uB3C4\uD574 \uC8FC\uC138\uC694.')}}
let cachedProgress:PersonalFarmProgressDto|undefined; let refreshRequest:Promise<PersonalFarmProgressDto>|undefined; let activeUserKey='';
const strings=(value:unknown,allowed:readonly string[])=>Array.isArray(value)&&value.every(item=>typeof item==='string'&&allowed.includes(item)); const nullableDate=(value:unknown)=>value===null||typeof value==='string';
export function isPersonalFarmProgressDto(value:unknown):value is PersonalFarmProgressDto{if(!value||typeof value!=='object')return false;const root=value as Record<string,unknown>,garden=root.gardenMission,bear=root.bearMission,farm=root.farm,visit=root.realVisit;if(!garden||typeof garden!=='object'||!bear||typeof bear!=='object'||!farm||typeof farm!=='object'||!visit||typeof visit!=='object')return false;const g=garden as Record<string,unknown>,b=bear as Record<string,unknown>,f=farm as Record<string,unknown>,v=visit as Record<string,unknown>;return strings(g.collectedFlowerIds,GARDEN_FLOWER_IDS)&&strings(g.plantedFlowerIds,GARDEN_FLOWER_IDS)&&typeof g.completed==='boolean'&&nullableDate(g.completedAt)&&strings(b.collectedFeedIds,BEAR_FEED_IDS)&&strings(b.completedFeedSpotIds,BEAR_FEED_SPOT_IDS)&&typeof b.completed==='boolean'&&nullableDate(b.completedAt)&&typeof f.unlocked==='boolean'&&strings(f.unlockedRewardIds,FARM_REWARD_IDS)&&strings(f.activeRewardIds,FARM_REWARD_IDS)&&['locked','cub','young','adult'].includes(String(f.bearGrowthStage))&&typeof v.garden==='object'&&typeof v.bearTree==='object'&&typeof root.layoutVersion==='number'&&typeof root.createdAt==='string'&&typeof root.updatedAt==='string'}
function publish(progress:PersonalFarmProgressDto){cachedProgress=progress;window.dispatchEvent(new CustomEvent<PersonalFarmProgressDto>(PERSONAL_FARM_PROGRESS_CHANGED,{detail:progress}));return progress}
export const getCachedPersonalFarmProgress=()=>cachedProgress; export const clearPersonalFarmProgressCache=()=>{cachedProgress=undefined;refreshRequest=undefined}; export function setPersonalFarmProgressUser(userKey:string){const next=userKey.trim().toLowerCase();if(next!==activeUserKey){activeUserKey=next;clearPersonalFarmProgressCache()}}; export const personalFarmErrorMessage=(error:unknown)=>error instanceof PersonalFarmApiError?error.message:'\uC11C\uBC84\uC5D0 \uC5F0\uACB0\uD560 \uC218 \uC5C6\uC2B5\uB2C8\uB2E4. \uC7A0\uC2DC \uD6C4 \uB2E4\uC2DC \uC2DC\uB3C4\uD574 \uC8FC\uC138\uC694.';
async function request(path:string,init?:RequestInit){let response:Response;try{response=await fetch(`${API_BASE_URL}/account/me/personal-farm${path}`,{...init,credentials:'include',headers:{...(init?.body?{'Content-Type':'application/json'}:{}),...init?.headers}})}catch{throw new PersonalFarmApiError('NETWORK_ERROR')}const body=await response.json().catch(()=>({})) as ApiErrorBody&ApiSuccessBody;if(!response.ok){const code=typeof body.error?.code==='string'?body.error.code:'REQUEST_FAILED';throw new PersonalFarmApiError(code,typeof body.error?.message==='string'?body.error.message:undefined,response.status)}if(body.success!==true||!isPersonalFarmProgressDto(body.data))throw new PersonalFarmApiError('INVALID_RESPONSE');return publish(body.data)}
export const getMyPersonalFarmProgress=()=>request(''); export function refreshPersonalFarmProgress(){return refreshRequest??(refreshRequest=getMyPersonalFarmProgress().finally(()=>{refreshRequest=undefined}))}; export const collectGardenFlower=(flowerId:GardenFlowerId)=>request(`/garden/collect/${encodeURIComponent(flowerId)}`,{method:'POST'}); export const plantGardenFlower=(flowerId:GardenFlowerId)=>request(`/garden/plant/${encodeURIComponent(flowerId)}`,{method:'POST'}); export const collectBearFeed=(feedId:BearFeedId)=>request(`/bear/collect/${encodeURIComponent(feedId)}`,{method:'POST'}); export const completeBearFeedSpot=(spotId:BearFeedSpotId)=>request(`/bear/feed/${encodeURIComponent(spotId)}`,{method:'POST'}); export const updateActiveFarmRewards=(rewardIds:FarmRewardId[])=>request('/rewards/active',{method:'PATCH',body:JSON.stringify({rewardIds})}); export const submitVisitMetadata=(mission:'garden'|'bearTree',metadata:Record<string,string>)=>request('/visit-proof',{method:'POST',body:JSON.stringify({mission,metadata})});
