import {API_BASE_URL} from '../config/api';
// Bear feeding is intentionally a separate action from completing feed spots.
import {BEAR_FEED_IDS,BEAR_FEED_SPOT_IDS,FARM_REWARD_IDS,GARDEN_FLOWER_IDS,type BearFeedId,type BearFeedSpotId,type FarmRewardId,type GardenFlowerId,type PersonalFarmProgressDto,type VisitMissionStatus,type VisitPlaceId} from '../../shared/personal-farm';
import {MemoryProgressRepository,MongoProgressRepository,ProgressService} from './personalFarmProgressRepository';
export const PERSONAL_FARM_PROGRESS_CHANGED='personal-farm-progress-changed';
type ApiErrorBody={error?:{code?:unknown;message?:unknown}};type ApiSuccessBody={success?:unknown;data?:unknown};
const errorMessages:Record<string,string>={UNAUTHENTICATED:'로그인이 필요합니다.',NETWORK_ERROR:'서버에 연결할 수 없습니다. 잠시 후 다시 시도해 주세요.',FARM_LOCKED:'수목원과 베어트리파크 미션을 완료하면 보상이 열립니다.',NATURE_CHAPTER_INCOMPLETE:'자연 체험을 완료한 후 이용할 수 있습니다.',VISIT_PROOF_ALREADY_SUBMITTED:'이미 사진을 제출했습니다.',VISIT_PROOF_NOT_AVAILABLE:'현재 제출할 수 없는 방문 미션입니다.',INVALID_FILE_TYPE:'이미지 파일만 등록할 수 있습니다.',FILE_TOO_LARGE:'사진 크기는 10MB 이하여야 합니다.'};
export class PersonalFarmApiError extends Error{constructor(readonly code:string,message?:string,readonly status=0){super(errorMessages[code]??message??'개인 팜 정보를 처리하지 못했습니다. 다시 시도해 주세요.')}}
let cachedProgress:PersonalFarmProgressDto|undefined;let refreshRequest:Promise<PersonalFarmProgressDto>|undefined;let activeUserKey='';let activeAuthenticated=true;
const memoryRepository=new MemoryProgressRepository();
const strings=(value:unknown,allowed:readonly string[])=>Array.isArray(value)&&value.every(item=>typeof item==='string'&&allowed.includes(item));const nullableDate=(value:unknown)=>value===null||typeof value==='string';
const isRecord=(value:unknown):value is Record<string,unknown>=>Boolean(value&&typeof value==='object'&&!Array.isArray(value));
const list=(value:unknown)=>Array.isArray(value)?value.filter((item):item is string=>typeof item==='string'):[];
const dateOrNull=(value:unknown)=>typeof value==='string'?value:null;
const visitStatus=(value:unknown):VisitMissionStatus=>value==='available'||value==='submitted'||value==='verified'||value==='rejected'?value:'locked';
const visitDefault=()=>({status:'locked' as const,submittedAt:null,reviewedAt:null,metadata:{},file:null});
export function normalizePersonalFarmProgress(value:unknown):PersonalFarmProgressDto|null{
  if(!isRecord(value))return null;
  const garden=isRecord(value.gardenMission)?value.gardenMission:{},bear=isRecord(value.bearMission)?value.bearMission:{},farm=isRecord(value.farm)?value.farm:{},nature=isRecord(value.natureChapter)?value.natureChapter:{},realVisit=isRecord(value.realVisit)?value.realVisit:{};
  const gardenVisit=isRecord(realVisit.garden)?realVisit.garden:visitDefault(),bearVisit=isRecord(realVisit.bearTree)?realVisit.bearTree:visitDefault();
  return {gardenMission:{collectedFlowerIds:list(garden.collectedFlowerIds).filter((id):id is GardenFlowerId=>(GARDEN_FLOWER_IDS as readonly string[]).includes(id)),plantedFlowerIds:list(garden.plantedFlowerIds).filter((id):id is GardenFlowerId=>(GARDEN_FLOWER_IDS as readonly string[]).includes(id)),completed:garden.completed===true,completedAt:dateOrNull(garden.completedAt),completedFlowerIds:list(garden.completedFlowerIds),requiredFlowerCount:typeof garden.requiredFlowerCount==='number'?garden.requiredFlowerCount:5,interestCompleted:garden.interestCompleted===true,interestCompletedAt:dateOrNull(garden.interestCompletedAt)},bearMission:{collectedFeedIds:list(bear.collectedFeedIds).filter((id):id is BearFeedId=>(BEAR_FEED_IDS as readonly string[]).includes(id)),completedFeedSpotIds:list(bear.completedFeedSpotIds).filter((id):id is BearFeedSpotId=>(BEAR_FEED_SPOT_IDS as readonly string[]).includes(id)),bearFed:bear.bearFed===true,bearFedAt:dateOrNull(bear.bearFedAt),completed:bear.completed===true,completedAt:dateOrNull(bear.completedAt)},farm:{unlocked:farm.unlocked===true,unlockedRewardIds:list(farm.unlockedRewardIds).filter((id):id is FarmRewardId=>(FARM_REWARD_IDS as readonly string[]).includes(id)),activeRewardIds:list(farm.activeRewardIds).filter((id):id is FarmRewardId=>(FARM_REWARD_IDS as readonly string[]).includes(id)),bearGrowthStage:['locked','cub','young','adult'].includes(String(farm.bearGrowthStage))?farm.bearGrowthStage as PersonalFarmProgressDto['farm']['bearGrowthStage']:'locked'},natureChapter:{gardenCompleted:nature.gardenCompleted===true,bearTreeCompleted:nature.bearTreeCompleted===true,completed:nature.completed===true,completedAt:dateOrNull(nature.completedAt),noticeShown:nature.noticeShown===true},realVisit:{garden:{...visitDefault(),...gardenVisit,status:visitStatus(gardenVisit.status)},bearTree:{...visitDefault(),...bearVisit,status:visitStatus(bearVisit.status)}},layoutVersion:typeof value.layoutVersion==='number'?value.layoutVersion:1,createdAt:typeof value.createdAt==='string'?value.createdAt:new Date(0).toISOString(),updatedAt:typeof value.updatedAt==='string'?value.updatedAt:new Date(0).toISOString()};
}
export function isPersonalFarmProgressDto(value:unknown):value is PersonalFarmProgressDto{if(!value||typeof value!=='object')return false;const root=value as Record<string,unknown>,g0=root.gardenMission,b0=root.bearMission,f0=root.farm,n0=root.natureChapter,v0=root.realVisit;if(!g0||typeof g0!=='object'||!b0||typeof b0!=='object'||!f0||typeof f0!=='object'||!n0||typeof n0!=='object'||!v0||typeof v0!=='object')return false;const g=g0 as Record<string,unknown>,b=b0 as Record<string,unknown>,f=f0 as Record<string,unknown>,n=n0 as Record<string,unknown>,v=v0 as Record<string,unknown>;return strings(g.collectedFlowerIds,GARDEN_FLOWER_IDS)&&strings(g.plantedFlowerIds,GARDEN_FLOWER_IDS)&&typeof g.completed==='boolean'&&nullableDate(g.completedAt)&&Array.isArray(g.completedFlowerIds)&&typeof g.requiredFlowerCount==='number'&&typeof g.interestCompleted==='boolean'&&nullableDate(g.interestCompletedAt)&&strings(b.collectedFeedIds,BEAR_FEED_IDS)&&strings(b.completedFeedSpotIds,BEAR_FEED_SPOT_IDS)&&typeof b.completed==='boolean'&&nullableDate(b.completedAt)&&typeof f.unlocked==='boolean'&&strings(f.unlockedRewardIds,FARM_REWARD_IDS)&&strings(f.activeRewardIds,FARM_REWARD_IDS)&&['locked','cub','young','adult'].includes(String(f.bearGrowthStage))&&typeof n.gardenCompleted==='boolean'&&typeof n.bearTreeCompleted==='boolean'&&typeof n.completed==='boolean'&&nullableDate(n.completedAt)&&typeof n.noticeShown==='boolean'&&typeof v.garden==='object'&&typeof v.bearTree==='object'&&typeof root.layoutVersion==='number'&&typeof root.createdAt==='string'&&typeof root.updatedAt==='string'}
function publish(progress:PersonalFarmProgressDto){cachedProgress=progress;window.dispatchEvent(new CustomEvent<PersonalFarmProgressDto>(PERSONAL_FARM_PROGRESS_CHANGED,{detail:progress}));return progress}
export function setPersonalFarmProgressMode(authenticated:boolean){if(activeAuthenticated!==authenticated){activeAuthenticated=authenticated;clearPersonalFarmProgressCache();if(!authenticated)memoryRepository.reset()}}
export function clearGuestPersonalFarmProgress(){if(!activeAuthenticated){memoryRepository.reset();clearPersonalFarmProgressCache()}}
export const getCachedPersonalFarmProgress=()=>cachedProgress;export const clearPersonalFarmProgressCache=()=>{cachedProgress=undefined;refreshRequest=undefined};export function setPersonalFarmProgressUser(userKey:string){const next=userKey.trim().toLowerCase();if(next!==activeUserKey){activeUserKey=next;clearPersonalFarmProgressCache()}};export const personalFarmErrorMessage=(error:unknown)=>error instanceof PersonalFarmApiError?error.message:'서버에 연결할 수 없습니다. 잠시 후 다시 시도해 주세요.';
async function request(path:string,init?:RequestInit){const endpoint=`${API_BASE_URL}/account/me/personal-farm${path}`;let response:Response;try{response=await fetch(endpoint,{...init,credentials:'include',headers:{...(init?.body?{'Content-Type':'application/json'}:{}),...init?.headers}})}catch{if(import.meta.env.DEV)console.error('[PersonalFarm]',{endpoint,status:0,errorCode:'NETWORK_ERROR'});throw new PersonalFarmApiError('NETWORK_ERROR')}const body=await response.json().catch(()=>({})) as ApiErrorBody&ApiSuccessBody;if(!response.ok){const code=typeof body.error?.code==='string'?body.error.code:'REQUEST_FAILED';if(import.meta.env.DEV)console.error('[PersonalFarm]',{endpoint,status:response.status,errorCode:code});throw new PersonalFarmApiError(code,typeof body.error?.message==='string'?body.error.message:undefined,response.status)}const normalized=body.success===true?normalizePersonalFarmProgress(body.data):null;if(!normalized||!isPersonalFarmProgressDto(normalized)){if(import.meta.env.DEV)console.error('[PersonalFarm]',{endpoint,status:response.status,errorCode:'INVALID_RESPONSE'});throw new PersonalFarmApiError('INVALID_RESPONSE',undefined,response.status)}return publish(normalized)}
const mongoService=new ProgressService(new MongoProgressRepository(request));
const memoryService=new ProgressService(memoryRepository);
const activeService=()=>activeAuthenticated?mongoService:memoryService;
export const removeGardenFlower=(flowerId:GardenFlowerId)=>activeService().removeFlower(flowerId).then(publish);
export const getMyPersonalFarmProgress=()=>activeService().get().then(publish);export function refreshPersonalFarmProgress(){return refreshRequest??(refreshRequest=getMyPersonalFarmProgress().finally(()=>{refreshRequest=undefined}))};export const collectGardenFlower=(flowerId:GardenFlowerId)=>activeService().collectFlower(flowerId).then(publish);export const plantGardenFlower=(flowerId:GardenFlowerId)=>activeService().plantFlower(flowerId).then(publish);export const collectBearFeed=(feedId:BearFeedId)=>activeService().collectFeed(feedId).then(publish);export const completeBearFeedSpot=(spotId:BearFeedSpotId)=>activeService().completeFeedSpot(spotId).then(publish);export const feedBear=()=>activeService().feedBear().then(publish);export const updateActiveFarmRewards=(rewardIds:FarmRewardId[])=>activeAuthenticated?request('/rewards/active',{method:'PATCH',body:JSON.stringify({rewardIds})}):getMyPersonalFarmProgress();export const acknowledgeNatureChapterNotice=()=>activeAuthenticated?request('/nature-chapter/notice-seen',{method:'POST'}):getMyPersonalFarmProgress();
export async function uploadVisitProof(placeId:VisitPlaceId,photo:File){if(!activeAuthenticated)return memoryRepository.submitVisit(placeId).then(publish);const form=new FormData();form.append('photo',photo);let response:Response;try{response=await fetch(`${API_BASE_URL}/account/me/personal-farm/visit-missions/${placeId}/proof`,{method:'POST',credentials:'include',body:form})}catch{throw new PersonalFarmApiError('NETWORK_ERROR')}const body=await response.json().catch(()=>({})) as ApiErrorBody&ApiSuccessBody;if(!response.ok){const code=typeof body.error?.code==='string'?body.error.code:'UPLOAD_FAILED';throw new PersonalFarmApiError(code,typeof body.error?.message==='string'?body.error.message:undefined,response.status)}const normalized=body.success===true?normalizePersonalFarmProgress(body.data):null;if(!normalized||!isPersonalFarmProgressDto(normalized))throw new PersonalFarmApiError('INVALID_RESPONSE');return publish(normalized)}
