import Phaser from 'phaser';import type { UserProfile } from '../../types';import type { Direction,MapId,PlayerState } from '../../../shared/socket-events';import { createAvatar,animateAvatar,type AvatarContainer } from '../entities/createAvatar';import { gameEvents } from '../events';import { socket } from '../systems/socketClient';
import { mapAssetManifest } from '../../data/mapAssetManifest';
import { characterSettings } from '../character/characterSettings';
import { directionFromMovement,directionYaw,motionState,movementYaw,normalizedMovement,shortestAngleDelta } from '../character/characterMotion';
interface Remote { avatar:AvatarContainer; targetX:number; targetY:number; targetYaw:number; state:PlayerState;lastAnimationAt:number }
interface SceneData {profile:UserProfile;mapId?:MapId}
const labels:Record<MapId,string>={town:'조치원 중심 마을','jochwon-station':'조치원역','traditional-market':'세종전통시장','jochwon-park':'조치원공원','college-street':'대학로'};
const MAIN={width:2400,height:1900};const DETAIL={width:1600,height:1100};
export class WorldScene extends Phaser.Scene{
 player!:AvatarContainer;cursors!:Phaser.Types.Input.Keyboard.CursorKeys;keys!:Record<string,Phaser.Input.Keyboard.Key>;profile!:UserProfile;mapId:MapId='town';remotes=new Map<string,Remote>();direction:Direction='down';isMoving=false;targetYaw=0;lastSent=0;lastSentX=Number.NaN;lastSentY=Number.NaN;lastSentYaw=0;lastSentMotion:'idle'|'walk'|'run'='idle';groundY=1100;obstacles:Phaser.Geom.Rectangle[]=[];assetLoadErrors:string[]=[];
 constructor(){super('world')}
 preload(){this.assetLoadErrors=[];this.load.on('loaderror',(file:Phaser.Loader.File)=>{const url=String(file.src);this.assetLoadErrors.push(`${file.key}: ${url}`);console.error('[Phaser asset load error]',{key:file.key,url,type:file.type})});this.load.on('complete',()=>console.log('[Phaser assets loaded successfully]'));Object.values(mapAssetManifest).forEach(asset=>this.load.svg(asset.key,asset.url))}
 init(data:SceneData){this.profile=data.profile;this.mapId=data.mapId??'town';this.obstacles=[]}
 create(){console.log('[Phaser WorldScene create start]',{mapId:this.mapId});try{const size=this.mapId==='town'?MAIN:DETAIL;this.physics.world.setBounds(0,0,size.width,size.height);this.cameras.main.setBounds(0,0,size.width,size.height);this.mapId==='town'?this.drawTown():this.drawDetail();const spawn=this.mapId==='town'?{x:1200,y:1050}:{x:800,y:880};this.groundY=spawn.y;this.player=createAvatar(this,spawn.x,spawn.y,this.profile.character,this.profile.nickname,1.05).setDepth(3000);this.cameras.main.startFollow(this.player,true,.08,.08);this.cursors=this.input.keyboard!.createCursorKeys();this.keys=this.input.keyboard!.addKeys('W,A,S,D,SHIFT,SPACE',false) as Record<string,Phaser.Input.Keyboard.Key>;this.bindInput();this.bindSocket();const join=()=>socket.emit('joinMap',{mapId:this.mapId,nickname:this.profile.nickname,appearance:this.profile.character,x:this.player.x,y:this.groundY});socket.on('connect',join);socket.connected?join():socket.connect();gameEvents.emit('location-changed',labels[this.mapId]);this.events.once(Phaser.Scenes.Events.SHUTDOWN,()=>{socket.off('connect',join);this.cleanup()});if(this.assetLoadErrors.length)this.showDevelopmentError(`일부 맵 에셋을 불러오지 못했습니다.\n${this.assetLoadErrors.join('\n')}`);console.log('[Phaser WorldScene create complete]',{mapId:this.mapId,assetLoadErrors:this.assetLoadErrors})}catch(error){console.error('[Phaser WorldScene create error]',error);this.showDevelopmentError(error instanceof Error?error.message:String(error))}}
 bindInput(){this.input.on('gameobjectdown',(_:unknown,obj:Phaser.GameObjects.GameObject)=>{const user=obj.getData('network-user');if(user)gameEvents.emit('network-user-selected',user);const destination=obj.getData('destination') as MapId|undefined;if(destination)this.changeMap(destination)});gameEvents.on('show-bubble',this.onShowBubble,this)}
 bindSocket(){socket.on('currentMapUsers',this.onCurrentUsers);socket.on('userJoined',this.onUserJoined);socket.on('userMoved',this.onUserMoved);socket.on('userLeft',this.onUserLeft);socket.on('nearbyChat',this.onNearbyChat)}
 cleanup(){gameEvents.off('show-bubble',this.onShowBubble,this);socket.off('currentMapUsers',this.onCurrentUsers);socket.off('userJoined',this.onUserJoined);socket.off('userMoved',this.onUserMoved);socket.off('userLeft',this.onUserLeft);socket.off('nearbyChat',this.onNearbyChat);this.remotes.forEach(r=>r.avatar.destroy());this.remotes.clear()}
 onCurrentUsers=(players:PlayerState[])=>{const ids=new Set(players.filter(p=>p.id!==socket.id).map(p=>p.id));for(const [id] of this.remotes)if(!ids.has(id))this.removeRemote(id);players.forEach(p=>this.addRemote(p))};onUserJoined=(p:PlayerState)=>this.addRemote(p);onUserMoved=(p:PlayerState)=>this.moveRemote(p);onUserLeft=(id:string)=>this.removeRemote(id);onNearbyChat=(m:{senderId:string;message:string})=>{const target=m.senderId===socket.id?this.player:this.remotes.get(m.senderId)?.avatar;if(target)this.showBubble(target,m.message);gameEvents.emit('chat-received',m)};onShowBubble=(message:string)=>this.showBubble(this.player,message);
 addRemote(state:PlayerState){if(state.id===socket.id)return;const targetYaw=Number.isFinite(state.yaw)?state.yaw:directionYaw(state.direction);const old=this.remotes.get(state.id);if(old){old.targetX=state.x;old.targetY=state.y;old.targetYaw=targetYaw;old.state=state;old.avatar.setData('network-user',state);return}const avatar=createAvatar(this,state.x,state.y,state.appearance,state.nickname,.98);avatar.setData('network-user',state);avatar.setData('visualYaw',targetYaw);this.remotes.set(state.id,{avatar,targetX:state.x,targetY:state.y,targetYaw,state,lastAnimationAt:0})}
 moveRemote(state:PlayerState){const remote=this.remotes.get(state.id);if(!remote)return this.addRemote(state);remote.targetX=state.x;remote.targetY=state.y;remote.targetYaw=Number.isFinite(state.yaw)?state.yaw:directionYaw(state.direction);remote.state=state;remote.avatar.setData('network-user',state)}removeRemote(id:string){this.remotes.get(id)?.avatar.destroy();this.remotes.delete(id)}
 drawTown(){this.cameras.main.setBackgroundColor('#bad8c5');this.add.rectangle(1200,950,2300,1800,0xb9d7c2).setStrokeStyle(10,0x92b39d);this.road(1200,950,2100,170);this.road(1200,950,180,1550);this.place(520,390,560,330,0x638f88,'조치원역','jochwon-station');this.place(1780,390,600,350,0xd58a58,'세종전통시장','traditional-market');this.place(1780,1500,620,360,0x73a66b,'조치원공원','jochwon-park');this.place(520,1500,620,360,0x6f81ad,'대학로','college-street');[[250,850],[500,850],[760,850],[1640,850],[1900,850],[2150,850],[930,300],[1470,300],[930,1600],[1470,1600]].forEach(([x,y])=>this.tree(x,y))}
 drawDetail(){this.cameras.main.setBackgroundColor('#dce5dd');const configs={
  'jochwon-station':{color:0x7b9997,title:'조치원역',features:['안내 데스크','대기 공간','마을 이동 안내']},
  'traditional-market':{color:0xd69a64,title:'세종전통시장',features:['시장 천막','먹거리 골목','상인 쉼터']},
  'jochwon-park':{color:0x7bad72,title:'조치원공원',features:['산책길','연못','벤치']},
  'college-street':{color:0x7c8eb5,title:'대학로',features:['카페 거리','소규모 광장','커뮤니티 공간']}
 } as const;const c=configs[this.mapId as Exclude<MapId,'town'>];this.add.rectangle(800,550,1500,1000,c.color,.34).setStrokeStyle(8,0xffffff,.7);this.road(800,600,1300,150);c.features.forEach((name,i)=>{const x=350+i*450;this.add.rectangle(x,350,270,190,c.color).setStrokeStyle(5,0xffffff).setInteractive().setData('feature',name);this.obstacles.push(new Phaser.Geom.Rectangle(x-135,255,270,190))});c.features.forEach((name,i)=>this.add.text(350+i*450,350,name,{fontSize:'18px',fontStyle:'bold',color:'#fff'}).setOrigin(.5));this.add.text(800,205,c.title,{fontFamily:'Noto Sans KR, sans-serif',fontSize:'32px',fontStyle:'bold',color:'#214f3f',align:'center'}).setOrigin(.5).setDepth(5000);const exit=this.add.rectangle(800,990,240,70,0x315b59).setStrokeStyle(4,0xffdf83).setInteractive({useHandCursor:true}).setData('destination','town');this.add.text(exit.x,exit.y,'메인 마을로 돌아가기',{fontSize:'17px',fontStyle:'bold',color:'#fff'}).setOrigin(.5)}
 place(x:number,y:number,w:number,h:number,color:number,label:string,destination:Exclude<MapId,'town'>){const asset=mapAssetManifest[destination];if(this.textures.exists(asset.key))this.add.image(x,y,asset.key).setDisplaySize(w,h);else this.drawFallbackPlace(x,y,w,h,color);this.obstacles.push(new Phaser.Geom.Rectangle(x-w/2+20,y-h/2+20,w-40,h-65));const door=this.add.rectangle(x,y+h/2-35,130,75,0x294c49,.82).setStrokeStyle(4,0xffdf83).setInteractive({useHandCursor:true}).setData('destination',destination);this.add.text(x,y-h/2+70,label,{fontFamily:'Noto Sans KR, sans-serif',fontSize:'32px',fontStyle:'bold',color:'#214f3f',align:'center'}).setOrigin(.5).setDepth(5000);this.add.text(door.x,door.y,'입장',{fontSize:'16px',fontStyle:'bold',color:'#fff'}).setOrigin(.5)}
 drawFallbackPlace(x:number,y:number,w:number,h:number,color:number){this.add.rectangle(x,y,w,h,color).setStrokeStyle(7,0xffffff,.8);this.add.polygon(x,y-h/2,[0,0,w/2,-70,w,0,w/2,70],color+0x101010);for(let offset=-w/3;offset<=w/3;offset+=100)this.add.rectangle(x+offset,y+20,54,70,0xd9edf0).setStrokeStyle(3,0xffffff)}
 showDevelopmentError(message:string){this.add.text(20,80,`맵 렌더링 오류\n${message}`,{fontFamily:'monospace',fontSize:'14px',color:'#ffffff',backgroundColor:'#9b2c2c',padding:{x:12,y:10},wordWrap:{width:620}}).setScrollFactor(0).setDepth(10000)}
 road(x:number,y:number,w:number,h:number){this.add.rectangle(x,y,w,h,0x768080).setStrokeStyle(8,0xe9dfbd);if(w>h)for(let px=x-w/2+60;px<x+w/2;px+=90)this.add.rectangle(px,y,42,5,0xfff3bf);else for(let py=y-h/2+60;py<y+h/2;py+=90)this.add.rectangle(x,py,5,42,0xfff3bf)}tree(x:number,y:number){this.add.rectangle(x,y+18,12,44,0x73513c);this.add.circle(x,y-12,32,0x4f9266).setStrokeStyle(4,0x87b879);this.obstacles.push(new Phaser.Geom.Rectangle(x-25,y-40,50,75))}
 changeMap(mapId:MapId){this.cameras.main.fadeOut(220,22,43,40);this.time.delayedCall(240,()=>this.scene.restart({profile:this.profile,mapId}))}
 update(time:number,deltaMs:number){const deltaSeconds=Math.min(deltaMs/1000,.05),active=['INPUT','TEXTAREA','SELECT'].includes(document.activeElement?.tagName??'');const movement=normalizedMovement({left:!active&&(this.cursors.left.isDown||this.keys.A.isDown),right:!active&&(this.cursors.right.isDown||this.keys.D.isDown),up:!active&&(this.cursors.up.isDown||this.keys.W.isDown),down:!active&&(this.cursors.down.isDown||this.keys.S.isDown)});this.isMoving=!!(movement.x||movement.y);const running=this.isMoving&&this.keys.SHIFT.isDown,state=motionState(movement,running);if(this.isMoving){this.targetYaw=movementYaw(movement);this.direction=directionFromMovement(movement,this.direction);const size=this.mapId==='town'?MAIN:DETAIL,speed=running?characterSettings.runSpeed:characterSettings.walkSpeed,nextX=Phaser.Math.Clamp(this.player.x+movement.x*speed*deltaSeconds,35,size.width-35),nextY=Phaser.Math.Clamp(this.groundY+movement.y*speed*deltaSeconds,90,size.height-35);if(this.canMove(nextX,this.groundY))this.player.x=nextX;if(this.canMove(this.player.x,nextY))this.groundY=nextY}this.player.y=this.groundY;animateAvatar(this.player,{targetYaw:this.targetYaw,movementX:movement.x,movementY:movement.y,motionState:state},deltaSeconds);this.player.setDepth(Math.floor(this.groundY)+2000);if(this.shouldSendMovement(time,state))socket.emit('userMoved',{mapId:this.mapId,x:this.player.x,y:this.groundY,direction:this.direction,isMoving:this.isMoving,yaw:this.targetYaw,motionState:state,timestamp:Date.now()});const interpolation=1-Math.exp(-12*deltaSeconds),animationInterval=1000/30;this.remotes.forEach(remote=>{remote.avatar.x=Phaser.Math.Linear(remote.avatar.x,remote.targetX,interpolation);remote.avatar.y=Phaser.Math.Linear(remote.avatar.y,remote.targetY,interpolation);remote.avatar.setDepth(Math.floor(remote.avatar.y)+2000);const visible=this.cameras.main.worldView.contains(remote.avatar.x,remote.avatar.y);remote.avatar.setVisible(visible);if(visible&&time-remote.lastAnimationAt>=animationInterval){const remoteState=remote.state.motionState??(remote.state.isMoving?'walk':'idle');animateAvatar(remote.avatar,{targetYaw:remote.targetYaw,movementX:Math.sin(remote.targetYaw),movementY:Math.cos(remote.targetYaw),motionState:remoteState},Math.min((time-remote.lastAnimationAt)/1000,.05));remote.lastAnimationAt=time}})}
 shouldSendMovement(time:number,state:'idle'|'walk'|'run'){const stateChanged=state!==this.lastSentMotion,moved=!Number.isFinite(this.lastSentX)||Math.hypot(this.player.x-this.lastSentX,this.groundY-this.lastSentY)>=2,turned=Math.abs(shortestAngleDelta(this.lastSentYaw,this.targetYaw))>=.04,heartbeat=time-this.lastSent>=1000;if(!stateChanged&&time-this.lastSent<67||!stateChanged&&!moved&&!turned&&!heartbeat)return false;this.lastSent=time;this.lastSentX=this.player.x;this.lastSentY=this.groundY;this.lastSentYaw=this.targetYaw;this.lastSentMotion=state;return true}
 canMove(x:number,y:number){const body=new Phaser.Geom.Rectangle(x-16,y-62,32,72);return !this.obstacles.some(wall=>Phaser.Geom.Intersects.RectangleToRectangle(body,wall))}
 showBubble(target:Phaser.GameObjects.Container,message:string){const bubble=this.add.text(target.x,target.y-105,message,{fontSize:'14px',color:'#183b36',backgroundColor:'#ffffff',padding:{x:10,y:7},wordWrap:{width:180}}).setOrigin(.5).setDepth(7000);this.tweens.add({targets:bubble,y:bubble.y-12,alpha:0,delay:3200,duration:800,onComplete:()=>bubble.destroy()})}
}
