import type { Server,Socket } from 'socket.io';import type { ClientToServerEvents,ServerToClientEvents,PlayerState,ChatMessage } from '../../../shared/socket-events.js';import { roomStore } from '../rooms/roomStore.js';
type IO=Server<ClientToServerEvents,ServerToClientEvents>;type Client=Socket<ClientToServerEvents,ServerToClientEvents>;
const clean=(value:string,max=180)=>value.trim().slice(0,max);
export function registerSocketHandlers(io:IO,socket:Client){
 socket.on('joinRoom',payload=>{const previous=roomStore.players.get(socket.id);if(previous){socket.leave(previous.mapId);socket.to(previous.mapId).emit('playerLeft',socket.id)}const player:PlayerState={id:socket.id,mapId:payload.mapId,x:payload.x,y:payload.y,direction:'down',isMoving:false,nickname:clean(payload.nickname,16)||'새 이웃',appearance:payload.appearance};roomStore.players.set(socket.id,player);socket.join(payload.mapId);socket.emit('roomState',roomStore.playersIn(payload.mapId).filter(p=>p.id!==socket.id));socket.to(payload.mapId).emit('playerJoined',player)});
 socket.on('movePlayer',payload=>{const player=roomStore.players.get(socket.id);if(!player||player.mapId!==payload.mapId)return;Object.assign(player,{x:payload.x,y:payload.y,direction:payload.direction,isMoving:payload.isMoving});socket.to(player.mapId).emit('playerMoved',player)});
 socket.on('sendNearbyChat',raw=>{const player=roomStore.players.get(socket.id),message=clean(raw);if(!player||!message)return;const data:ChatMessage={id:crypto.randomUUID(),mapId:player.mapId,senderId:socket.id,nickname:player.nickname,message,createdAt:Date.now(),channel:'nearby'};io.to(player.mapId).emit('nearbyChat',data)});
 socket.on('requestDirect',toId=>{const from=roomStore.players.get(socket.id),to=roomStore.players.get(toId);if(!from||!to||from.mapId!==to.mapId)return socket.emit('errorMessage','같은 맵에 있는 사용자에게만 신청할 수 있어요.');const requestId=crypto.randomUUID();roomStore.pendingDirect.set(requestId,{fromId:from.id,toId});io.to(toId).emit('directRequest',{requestId,from:{id:from.id,nickname:from.nickname},toId})});
 socket.on('respondDirect',({requestId,accepted})=>{const req=roomStore.pendingDirect.get(requestId);if(!req||req.toId!==socket.id)return;roomStore.pendingDirect.delete(requestId);io.to(req.fromId).emit('directResponse',{requestId,fromId:socket.id,accepted});io.to(req.toId).emit('directResponse',{requestId,fromId:req.fromId,accepted})});
 socket.on('createGroup',({name,inviteeIds})=>{const owner=roomStore.players.get(socket.id);if(!owner)return;const group=roomStore.createGroup(owner,clean(name,30),inviteeIds);group.memberIds.forEach(id=>{io.sockets.sockets.get(id)?.join(group.id);io.to(id).emit('groupCreated',group)})});
 socket.on('joinGroup',groupId=>{const player=roomStore.players.get(socket.id),group=roomStore.groups.get(groupId);if(!player||!group||player.mapId!==group.mapId)return;group.memberIds=[...new Set([...group.memberIds,socket.id])];socket.join(group.id);io.to(group.id).emit('groupUpdated',group)});
 socket.on('sendGroupChat',({groupId,message:raw})=>{const player=roomStore.players.get(socket.id),group=roomStore.groups.get(groupId),message=clean(raw);if(!player||!group||!group.memberIds.includes(socket.id)||!message)return;io.to(group.id).emit('nearbyChat',{id:crypto.randomUUID(),mapId:player.mapId,senderId:socket.id,nickname:player.nickname,message,createdAt:Date.now(),channel:'group'})});
 socket.on('disconnect',()=>{const player=roomStore.players.get(socket.id);if(player)socket.to(player.mapId).emit('playerLeft',socket.id);roomStore.removePlayer(socket.id)});
}
