import { useEffect,useMemo,useState,type CSSProperties,type FormEvent } from 'react';
import { ArrowRight,Bot,Check,Heart,MapPin,MessageCircle,Plus,Route,Search,Sparkles,Users,X } from 'lucide-react';
import type { PlayerState } from '../../shared/socket-events';
import { API_BASE_URL } from '../config/api';
import { gameEvents } from '../game/events';
import type { UserProfile } from '../types';
import { CharacterPreview } from './CharacterPreview';
import './CampusCommunicationHub.css';

export type CampusHubTab='people'|'clubs'|'recruit'|'government';
type MatchResult={totalScore:number;reason:string;sharedInterests:string[];sharedPurposes:string[];sharedExperienceRecords:string[]};
type ClubMember={userId:string;name:string};
type Club={id:string;name:string;description:string;category:string;color:string;ownerId:string;ownerName:string;members:ClubMember[]};
type Recruitment={id:string;author:string;title:string;content:string;likes:number;likedBy:string[];createdAt:string};

const tabs:Array<{id:CampusHubTab;icon:string;label:string;copy:string}>=[
  {id:'people',icon:'🏛️',label:'학생회관',copy:'AI 이웃 추천'},
  {id:'clubs',icon:'🎪',label:'동아리 거리',copy:'AI와 운영하는 모임'},
  {id:'recruit',icon:'📣',label:'캠퍼스 광장',copy:'AI가 연결하는 모집'},
  {id:'government',icon:'🗺️',label:'정부청사 연계',copy:'함께 코스 만들기'},
];
const defaultClubs=[
  {name:'세종 축제 기획부',category:'문화·예술',description:'세종의 밤을 빛낼 축제 아이디어를 함께 만들어요.',color:'#e59a52'},
  {name:'식물사진 동아리',category:'문화·예술',description:'계절마다 달라지는 식물과 풍경을 사진으로 기록해요.',color:'#55a879'},
  {name:'세종 맛집 탐방부',category:'친목',description:'동네의 숨은 맛집을 찾고 함께 방문해요.',color:'#dd7b61'},
  {name:'카페 산책부',category:'친목',description:'산책하기 좋은 길과 편안한 카페를 이어 걸어요.',color:'#8b72c8'},
  {name:'스마트도시 연구회',category:'스터디',description:'세종의 도시 기술과 공간을 가볍게 탐구해요.',color:'#438daf'},
  {name:'친환경 여행 동아리',category:'봉사',description:'자연을 아끼며 즐기는 세종 여행법을 나눠요.',color:'#4f9b8c'},
];
const activityOptions=[
  {id:'night-festival',emoji:'🌙',label:'야간축제',copy:'빛과 공연이 있는 밤 산책'},
  {id:'plant-photo',emoji:'📷',label:'식물사진',copy:'수목원에서 계절 기록'},
  {id:'cafe-tour',emoji:'☕',label:'카페투어',copy:'동네 카페와 디저트 탐방'},
  {id:'smart-city',emoji:'🏙️',label:'스마트도시 탐방',copy:'도시 기술과 건축 둘러보기'},
];
const userIdFor=(name:string)=>`community-user-${name.trim().toLowerCase().replace(/\s+/g,'-')||'anonymous'}`;
const readError=async(response:Response)=>{try{const body=await response.json() as {message?:string;error?:string};return body.message??body.error??'요청을 처리하지 못했어요.'}catch{return '요청을 처리하지 못했어요.'}};

export function CampusCommunicationHub({profile,players,initialTab='people',onClose,onOpenBoard,onProfile,onDirectChat,onClubChat,onTour,onGovernment}:{profile:UserProfile;players:PlayerState[];initialTab?:CampusHubTab;onClose:()=>void;onOpenBoard:()=>void;onProfile:(player:PlayerState)=>void;onDirectChat:(player:PlayerState)=>void;onClubChat:(club:Club)=>void;onTour:(player:PlayerState)=>void;onGovernment:()=>void}){
  const [tab,setTab]=useState<CampusHubTab>(initialTab),[matches,setMatches]=useState<Record<string,MatchResult>>({}),[clubs,setClubs]=useState<Club[]>([]),[recruitments,setRecruitments]=useState<Recruitment[]>([]);
  const [loading,setLoading]=useState(true),[notice,setNotice]=useState(''),[clubComposer,setClubComposer]=useState(false),[recruitComposer,setRecruitComposer]=useState(false);
  const [portalEditorOpen,setPortalEditorOpen]=useState(false);
  const [clubName,setClubName]=useState(''),[clubDescription,setClubDescription]=useState(''),[recruitTitle,setRecruitTitle]=useState(''),[recruitTags,setRecruitTags]=useState('자연, 카페, 사진'),[recruitSize,setRecruitSize]=useState('2~4명');
  const [vote,setVote]=useState(()=>localStorage.getItem(`campus-activity-vote:${profile.nickname}`)??'');
  const userId=useMemo(()=>userIdFor(profile.nickname),[profile.nickname]);
  useEffect(()=>setTab(initialTab),[initialTab]);
  useEffect(()=>{let active=true;Promise.all(players.filter(player=>player.matchProfile).map(async player=>{const response=await fetch(`${API_BASE_URL}/matching/score`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({first:profile,second:player.matchProfile})});return [player.id,response.ok?await response.json():null] as const})).then(entries=>{if(active)setMatches(Object.fromEntries(entries.filter((entry):entry is readonly[string,MatchResult]=>Boolean(entry[1]))))}).catch(()=>{});return()=>{active=false}},[players,profile]);
  const loadHub=async()=>{setLoading(true);try{const [clubResponse,postResponse]=await Promise.all([fetch(`${API_BASE_URL}/clubs`),fetch(`${API_BASE_URL}/community`)]);if(clubResponse.ok)setClubs(await clubResponse.json() as Club[]);if(postResponse.ok){const posts=await postResponse.json() as Array<Recruitment&{category:string}>;setRecruitments(posts.filter(post=>post.category==='모임·행사'))}}finally{setLoading(false)}};
  useEffect(()=>{void loadHub()},[]);
  const rankedPlayers=useMemo(()=>[...players].sort((a,b)=>(matches[b.id]?.totalScore??0)-(matches[a.id]?.totalScore??0)),[matches,players]);
  const recommendedRecruitPlayers=rankedPlayers.slice(0,2);
  const joinedClubs=clubs.filter(club=>club.members.some(member=>member.userId===userId));
  const chooseVote=(id:string)=>{setVote(id);localStorage.setItem(`campus-activity-vote:${profile.nickname}`,id);setNotice('투표가 저장됐어요. 정부청사에서 장소를 정할 때 활용할 수 있어요.')};
  const seedClub=async(template:typeof defaultClubs[number])=>{const response=await fetch(`${API_BASE_URL}/clubs`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...template,ownerId:userId,ownerName:profile.nickname})});if(!response.ok)throw new Error(await readError(response));const created=await response.json() as Club;setClubs(current=>[created,...current])};
  const createClub=async(event:FormEvent)=>{event.preventDefault();if(!clubName.trim())return;try{await seedClub({name:clubName,description:clubDescription,category:'친목',color:'#4f9b8c'});setClubName('');setClubDescription('');setClubComposer(false);setNotice('새 동아리방이 열렸어요.')}catch(error){setNotice(error instanceof Error?error.message:'동아리를 만들지 못했어요.')}};
  const joinClub=async(club:Club)=>{try{const response=await fetch(`${API_BASE_URL}/clubs/${club.id}/join`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({userId,userName:profile.nickname})});if(!response.ok)throw new Error(await readError(response));const updated=await response.json() as Club;setClubs(current=>current.map(item=>item.id===updated.id?updated:item));setNotice(`${club.name}에 가입했어요.`)}catch(error){setNotice(error instanceof Error?error.message:'가입하지 못했어요.')}};
  const createRecruitment=async(event:FormEvent)=>{event.preventDefault();if(!recruitTitle.trim())return;const content=`관심 태그: ${recruitTags.trim()}\n모집 인원: ${recruitSize}\n관심 있어요를 누른 뒤 1대1 대화로 연결해요.`;try{const response=await fetch(`${API_BASE_URL}/community`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({author:profile.nickname,title:recruitTitle,content,category:'모임·행사'})});if(!response.ok)throw new Error(await readError(response));const created=await response.json() as Recruitment;setRecruitments(current=>[created,...current]);setRecruitTitle('');setRecruitComposer(false);setNotice('캠퍼스 광장에 모집 카드가 등록됐어요.')}catch(error){setNotice(error instanceof Error?error.message:'모집 카드를 등록하지 못했어요.')}};
  const toggleInterest=async(item:Recruitment)=>{const response=await fetch(`${API_BASE_URL}/community/${item.id}/like`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({userId})});if(!response.ok)return setNotice(await readError(response));const result=await response.json() as {likes:number;likedBy:string[];liked:boolean};setRecruitments(current=>current.map(post=>post.id===item.id?{...post,likes:result.likes,likedBy:result.likedBy}:post));setNotice(result.liked?'모집자에게 관심 신호를 보냈어요.':'관심 표시를 취소했어요.')};
  return <div className="campus-hub-overlay"><section className="campus-hub" aria-label="공동캠퍼스 커뮤니케이션 허브">
    <header className="campus-hub-header"><div><span><Users size={18}/></span><div><small>AI COMMUNICATION CAMPUS</small><h1>AI가 사람을 연결하고, 함께 세종을 경험하게 해요</h1><p>취향 분석부터 동아리 운영, 동행 모집, 공동 여행 코스까지 하나의 여정으로 이어집니다.</p></div></div><button type="button" onClick={onClose} aria-label="공동캠퍼스 닫기"><X size={20}/></button></header>
    <div className="campus-hub-body"><nav className="campus-hub-nav">{tabs.map(item=><button type="button" className={tab===item.id?'active':''} onClick={()=>setTab(item.id)} key={item.id}><i>{item.icon}</i><span><b>{item.label}</b><small>{item.copy}</small></span><ArrowRight size={15}/></button>)}<button type="button" className="campus-board-link" onClick={onOpenBoard}><Search size={15}/><span><b>전체 게시판</b><small>글·댓글 자세히 보기</small></span><ArrowRight size={15}/></button><button type="button" className="campus-portal-editor-toggle" onClick={()=>setPortalEditorOpen(value=>!value)}><MapPin size={15}/><span><b>포탈 위치 고정</b><small>현재 캐릭터 좌표에 저장</small></span><ArrowRight size={15}/></button><aside><Sparkles size={17}/><div><b>오늘의 캠퍼스</b><span>현재 {players.length+1}명 · 동아리 {clubs.length}개</span></div></aside></nav>
      <main className="campus-hub-content">
        {portalEditorOpen&&<section className="campus-portal-editor"><header><div><small>PORTAL POSITION EDITOR</small><b>현재 캐릭터 위치에 포탈 고정</b><p>허브를 닫고 원하는 곳으로 이동한 뒤 다시 열어 저장하세요.</p></div><button type="button" onClick={()=>setPortalEditorOpen(false)}><X size={15}/></button></header><div>{tabs.map(item=><button type="button" key={item.id} onClick={()=>{gameEvents.emit('campus-feature-portal-position-save',item.id);setNotice(`${item.label} 포탈을 현재 위치에 고정했어요.`)}}><span>{item.icon}</span><div><b>{item.label}</b><small>{item.copy}</small></div><MapPin size={14}/></button>)}</div></section>}
        {tab==='people'&&<><div className="campus-section-title"><div><small>① 중앙 학생회관</small><h2>나와 잘 맞는 이웃 추천</h2><p>지금 접속한 사람의 공개 기록과 관심사를 바탕으로 추천해요.</p></div><span className="campus-live"><i/> LIVE {players.length}</span></div>{!rankedPlayers.length?<div className="campus-empty"><span>👋</span><b>다른 이웃을 기다리고 있어요</b><p>새로운 사용자가 공동캠퍼스에 들어오면 추천 카드가 표시됩니다.</p></div>:<div className="campus-people-grid">{rankedPlayers.map((player,index)=>{const match=matches[player.id],common=[...(match?.sharedExperienceRecords??[]),...(match?.sharedInterests??[]),...(match?.sharedPurposes??[])].slice(0,4);return <article className="campus-person-card" key={player.id}><div className="campus-person-rank">{index===0?'BEST MATCH':`추천 ${index+1}`}</div><div className="campus-person-main"><CharacterPreview parts={player.appearance} small/><div><h3>{player.nickname}</h3><p>{match?`${match.totalScore}% 비슷한 이웃이에요`:'공개 취향을 확인하고 있어요'}</p></div><strong>{match?.totalScore??'–'}<small>%</small></strong></div><div className="campus-match-reason"><Sparkles size={14}/><span>{match?.reason??'공개 프로필을 바탕으로 대화를 시작해 보세요.'}</span></div><div className="campus-common-tags">{common.length?common.map(value=><span key={value}>#{value.replace(/^.*?:\\s*/, '')}</span>):<span>#새로운_이웃</span>}</div><div className="campus-person-actions"><button type="button" onClick={()=>onProfile(player)}>프로필 보기</button><button type="button" className="primary-action" onClick={()=>onDirectChat(player)}><MessageCircle size={14}/> 1대1 대화</button><button type="button" disabled={!joinedClubs.length} title={joinedClubs.length?'첫 번째 가입 동아리로 초대합니다.':'먼저 동아리에 가입해 주세요.'} onClick={()=>onClubChat({...joinedClubs[0],members:[...joinedClubs[0].members,{userId:player.id,name:player.nickname}]})}>동아리 초대</button><button type="button" onClick={()=>onTour(player)}><MapPin size={14}/> 같이 둘러보기</button></div></article>})}</div>}</>}
        {tab==='clubs'&&<><div className="campus-section-title"><div><small>② 동아리 거리</small><h2>AI와 운영하는 관심사별 동아리</h2><p>운영 도우미가 인기 기록을 요약하고, 오늘의 투표와 다음 대화 주제를 제안해요.</p></div><button type="button" className="campus-create-button" onClick={()=>setClubComposer(value=>!value)}><Plus size={15}/> 동아리 만들기</button></div>{clubComposer&&<form className="campus-inline-form" onSubmit={createClub}><input value={clubName} onChange={event=>setClubName(event.target.value)} placeholder="동아리 이름"/><input value={clubDescription} onChange={event=>setClubDescription(event.target.value)} placeholder="어떤 활동을 함께하나요?"/><button>만들기</button></form>}<div className="campus-club-grid">{clubs.map((club,index)=>{const joined=club.members.some(member=>member.userId===userId),suggestion=activityOptions[index%activityOptions.length];return <article key={club.id} style={{'--club-color':club.color} as CSSProperties}><span>{club.category}</span><div className="campus-club-icon">{club.name.slice(0,1)}</div><h3>{club.name}</h3><p>{club.description}</p><small><Users size={13}/> 멤버 {club.members.length}명 · {club.ownerName}</small><aside className="campus-ai-helper"><b><Bot size={13}/> AI 운영 도우미</b><p>인기 기록 · {suggestion.copy}</p><button type="button" className={vote===suggestion.id?'selected':''} onClick={()=>chooseVote(suggestion.id)}>{vote===suggestion.id?<Check size={12}/>:<Sparkles size={12}/>} {suggestion.label} 제안에 투표</button></aside><button type="button" className={joined?'joined':''} onClick={()=>joined?onClubChat(club):void joinClub(club)}>{joined?<><MessageCircle size={14}/> 동아리 채팅방 열기</>:<><Plus size={14}/> 가입하기</>}</button></article>})}{!loading&&defaultClubs.filter(template=>!clubs.some(club=>club.name===template.name)).map((template,index)=>{const suggestion=activityOptions[index%activityOptions.length];return <article className="campus-club-template" key={template.name} style={{'--club-color':template.color} as CSSProperties}><span>{template.category}</span><div className="campus-club-icon">{template.name.slice(0,1)}</div><h3>{template.name}</h3><p>{template.description}</p><aside className="campus-ai-helper"><b><Bot size={13}/> AI 운영 도우미</b><p>추천 주제 · {suggestion.copy}</p></aside><button type="button" onClick={()=>void seedClub(template)}><Plus size={14}/> 이 동아리 개설하기</button></article>})}</div></>}
        {tab==='recruit'&&<><div className="campus-section-title"><div><small>③ 캠퍼스 광장</small><h2>함께 갈 사람을 찾고 AI 추천으로 연결해요</h2><p>관심 신호를 보내고, 공개 취향이 잘 맞는 이웃과 바로 대화를 시작할 수 있어요.</p></div><button type="button" className="campus-create-button" onClick={()=>setRecruitComposer(value=>!value)}><Plus size={15}/> 모집 카드 만들기</button></div>{recruitComposer&&<form className="campus-recruit-form" onSubmit={createRecruitment}><label>모집 문구<input value={recruitTitle} onChange={event=>setRecruitTitle(event.target.value)} placeholder="주말에 세종 카페와 수목원을 함께 가실 분?"/></label><label>관심 태그<input value={recruitTags} onChange={event=>setRecruitTags(event.target.value)} placeholder="자연, 카페, 사진"/></label><label>모집 인원<select value={recruitSize} onChange={event=>setRecruitSize(event.target.value)}><option>2명</option><option>2~4명</option><option>3~5명</option><option>제한 없음</option></select></label><button>광장에 등록</button></form>}<div className="campus-recruit-list">{recruitments.map(item=>{const liked=item.likedBy?.includes(userId),lines=item.content.split('\n'),recommended=recommendedRecruitPlayers[0];return <article key={item.id}><header><div><span>{item.author.slice(0,1)}</span><div><b>{item.author}</b><small>함께할 이웃을 찾고 있어요</small></div></div><i>모집 중</i></header><h3>“{item.title}”</h3>{lines.map(line=><p key={line}>{line}</p>)}<div className="campus-recruit-ai"><Sparkles size={13}/><span><b>AI 추천 대상</b>{recommendedRecruitPlayers.length?recommendedRecruitPlayers.map(player=>`${player.nickname} ${matches[player.id]?.totalScore??'–'}%`).join(' · '):'취향이 맞는 이웃을 찾는 중이에요'}</span></div><footer><span><Users size={14}/> 관심 {item.likes}명</span><div><button type="button" className={liked?'liked':''} onClick={()=>void toggleInterest(item)}><Heart size={14} fill={liked?'currentColor':'none'}/> {liked?'관심 전달됨':'관심 있어요'}</button><button type="button" disabled={!recommended} onClick={()=>recommended&&onDirectChat(recommended)}><MessageCircle size={14}/> 추천 이웃과 채팅</button></div></footer></article>})}{!recruitments.length&&!loading&&<div className="campus-empty"><span>📣</span><b>첫 모집 카드를 만들어 보세요</b><p>AI가 관심 태그와 공개 취향을 비교해 잘 맞는 이웃에게 추천합니다.</p></div>}</div></>}
        {tab==='government'&&<><div className="campus-section-title"><div><small>④ 정부청사 연계</small><h2>대화를 실제 세종 여행 코스로 완성해요</h2><p>1대1 또는 동아리에서 합의한 뒤 같은 코스를 함께 편집하고 실제 방문으로 이어갑니다.</p></div><span className="campus-status-pill">공동 편집</span></div><section className="campus-government-flow"><article><span>1</span><div><small>1대1 · 동아리 대화</small><b>같이 코스 만들기</b><p>함께 갈 사람과 관심 주제를 먼저 확인해요.</p></div></article><ArrowRight size={20}/><article><span>2</span><div><small>정부청사 계획 공간</small><b>동일한 코스 공동 편집</b><p>장소와 순서, 시간을 함께 조정해요.</p></div></article><ArrowRight size={20}/><article><span>3</span><div><small>세종 현장</small><b>저장하고 실제 방문</b><p>완성한 코스를 대화방에 공유해요.</p></div></article></section><div className="campus-government-layout"><section className="campus-government-vote"><header><Sparkles size={17}/><div><small>AI가 모은 오늘의 관심사</small><b>코스 주제를 하나 골라보세요</b></div></header>{activityOptions.map((option,index)=>{const selected=vote===option.id,count=[8,6,5,3][index]+(selected?1:0);return <button type="button" className={selected?'selected':''} onClick={()=>chooseVote(option.id)} key={option.id}><span>{option.emoji}</span><div><b>{option.label}</b><small>{option.copy} · {count}명 선택</small></div>{selected?<Check size={17}/>:<ArrowRight size={15}/>}</button>})}</section><section className="campus-government-cta"><Route size={34}/><small>AI CO-CREATION JOURNEY</small><h3>채팅을 넘어<br/>함께 경험하는 세종으로</h3><p>선택한 주제와 대화 맥락을 바탕으로 정부청사에서 공동 여행 코스를 시작합니다.</p><button type="button" onClick={onGovernment}>정부청사에서 코스 만들기 <ArrowRight size={15}/></button><em>1대1 대화에서는 상대방 수락 후 같은 세션으로 연결돼요.</em></section></div></>}
      </main>
    </div>
    {notice&&<button type="button" className="campus-hub-notice" onClick={()=>setNotice('')}>{notice}<X size={13}/></button>}
  </section></div>;
}
