import {useEffect,useMemo,useState} from 'react';
import type {MapId} from '../../shared/socket-events';
import type {PersonalFarmProgressDto} from '../../shared/personal-farm';
import {gameEvents} from '../game/events';
import {getFlowerInterestSnapshot} from '../services/flowerInterestTracker';
import {formatFlowerSeconds,topFlowerInterests,type FlowerProfileCard} from '../services/flowerInterestProfile';
import {acknowledgeNatureChapterNotice,getCachedPersonalFarmProgress} from '../services/personalFarmApi';
import {uploadVisitProof} from '../services/personalFarmApi';

export function MemoryTreeInterestExperience({mapId,authenticated}:{mapId:MapId;authenticated:boolean}){
  const [nearby,setNearby]=useState(false),[open,setOpen]=useState(false),[visitOpen,setVisitOpen]=useState(false);
  const [records,setRecords]=useState(()=>getFlowerInterestSnapshot());
  const [progress,setProgress]=useState<PersonalFarmProgressDto|undefined>(()=>getCachedPersonalFarmProgress());
  const [loadState,setLoadState]=useState<'idle'|'loading'|'ready'|'error'|'expired'>('idle');
  useEffect(()=>{
    const proximity=(value:{objectName:string}|null)=>setNearby(Boolean(value));
    const flowers=(event:Event)=>{const value=(event as CustomEvent<unknown>).detail;if(Array.isArray(value))setRecords(value as ReturnType<typeof getFlowerInterestSnapshot>)};
    const loading=(event:Event)=>setLoadState((event as CustomEvent<'loading'|'ready'|'error'|'expired'>).detail);
    const farm=(event:Event)=>{const value=(event as CustomEvent<PersonalFarmProgressDto>).detail;if(value)setProgress(value)};
    gameEvents.on('personal-farm-memory-tree-proximity-changed',proximity);window.addEventListener('flower-interest-updated',flowers);window.addEventListener('flower-interest-load-state',loading);window.addEventListener('personal-farm-progress-changed',farm);window.addEventListener('personal-farm-progress-refresh',farm);
    return()=>{gameEvents.off('personal-farm-memory-tree-proximity-changed',proximity);window.removeEventListener('flower-interest-updated',flowers);window.removeEventListener('flower-interest-load-state',loading);window.removeEventListener('personal-farm-progress-changed',farm);window.removeEventListener('personal-farm-progress-refresh',farm)};
  },[]);
  useEffect(()=>{setOpen(false);setVisitOpen(false);setRecords([]);setProgress(undefined);setLoadState(authenticated?'loading':'ready')},[authenticated]);
  useEffect(()=>{if(mapId!=='personal-farm'){setOpen(false);setVisitOpen(false);setNearby(false)}},[mapId]);
  useEffect(()=>{if(!nearby||mapId!=='personal-farm')return;const key=(event:KeyboardEvent)=>{if(event.repeat||event.key.toLowerCase()!=='e')return;const target=event.target;if(target instanceof HTMLInputElement||target instanceof HTMLTextAreaElement||target instanceof HTMLSelectElement)return;event.preventDefault();setOpen(true)};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key)},[mapId,nearby]);
  const top=useMemo(()=>topFlowerInterests(records),[records]);
  if(mapId!=='personal-farm')return null;
  const highest=top[0],longestInfo=[...top].sort((a,b)=>b.totalInfoViewSeconds-a.totalInfoViewSeconds)[0],longestNearby=[...top].sort((a,b)=>b.totalNearbySeconds-a.totalNearbySeconds)[0];
  return <>{nearby&&!open&&<button type="button" className="memory-tree-interest-prompt" onClick={()=>setOpen(true)}><span>🌳</span><div><small>개인 팜 중앙 기억나무</small><b>[E] 기억나무 살펴보기</b></div></button>}{open&&<div className="memory-tree-interest-overlay" role="dialog" aria-modal="true"><section className="memory-tree-interest-modal"><button type="button" className="memory-tree-interest-close" onClick={()=>setOpen(false)} aria-label="닫기">×</button><small>개인 팜 중앙 기억나무</small><h2>수목원에서 남긴 꽃의 기억입니다.</h2>{loadState==='loading'&&<p>꽃의 기억을 불러오는 중입니다.</p>}{loadState==='expired'&&<p>다시 로그인해 주세요.</p>}{loadState==='error'&&<p>꽃의 기억을 불러오지 못했습니다.</p>}{loadState!=='loading'&&loadState!=='error'&&loadState!=='expired'&&!top.length&&<p>아직 기록된 꽃의 기억이 없습니다.</p>}{top.length>0&&<><div className="memory-tree-interest-summary"><span>가장 관심도가 높은 꽃<strong>{highest?.displayName}</strong></span><span>가장 오래 본 꽃<strong>{longestInfo?.displayName}</strong></span><span>가장 오래 머문 꽃<strong>{longestNearby?.displayName}</strong></span><span>탐색한 꽃 종류<strong>{records.length}종</strong></span></div><div className="memory-tree-interest-grid">{top.map(flower=><FlowerCard key={flower.flowerId} flower={flower}/>)}</div></>}{progress&&<NatureChapterSection progress={progress} onOpenVisits={()=>setVisitOpen(true)}/>}</section></div>}{visitOpen&&<VisitMissionOverlay progress={progress} onClose={()=>setVisitOpen(false)}/>}</>;
}
function NatureChapterSection({progress,onOpenVisits}:{progress:PersonalFarmProgressDto;onOpenVisits:()=>void}){const {natureChapter:n,gardenMission:g,bearMission:b}=progress;const [notice,setNotice]=useState(n.completed&&!n.noticeShown);const title=n.completed?'자연 체험 완료!':n.gardenCompleted?'수목원 꽃의 기억이 완성되었습니다.':n.bearTreeCompleted?'베어트리파크 생태 체험을 완료했습니다.':'자연 체험 진행 중';return <section className="memory-tree-nature-chapter">{notice&&<div className="memory-tree-completion-notice"><h3>자연 체험을 모두 완료했습니다!</h3><p>이제 실제 수목원과 베어트리파크 방문 미션에 도전할 수 있습니다.</p><button type="button" onClick={()=>{setNotice(false);void acknowledgeNatureChapterNotice()}}>기억나무에서 확인하기</button><button type="button" onClick={()=>{setNotice(false);void acknowledgeNatureChapterNotice()}}>닫기</button></div>}<h3>{title}</h3><p>수목원 꽃 탐색: {g.completedFlowerIds.length}/{g.requiredFlowerCount}</p><p>베어트리파크 먹이 체험: {b.completedFeedSpotIds.length}/5</p>{n.completed&&<><p>수목원과 베어트리파크의 체험이 개인 팜에 기록되었습니다.</p><button type="button" onClick={onOpenVisits}>실제 방문 미션 보기</button></>}</section>}
function VisitMissionOverlay({progress,onClose}:{progress?:PersonalFarmProgressDto;onClose:()=>void}){const available=Boolean(progress?.natureChapter.completed);const missions:[string,string][]=[['수목원','수목원을 직접 방문하고 가상 공간에서 관심 있게 본 꽃을 찾아보세요.'],['베어트리파크','베어트리파크를 직접 방문하고 가상 먹이 체험에서 만난 곰과 생태 공간을 관찰해 보세요.']];return <div className="memory-tree-visit-overlay" role="dialog" aria-modal="true"><section className="memory-tree-visit-modal"><button type="button" onClick={onClose} aria-label="닫기">×</button><h2>실제 방문 미션</h2>{missions.map(([name,description],index)=>{const place=index===0?'garden':'bearTree';const mission=place==='garden'?progress?.realVisit.garden:progress?.realVisit.bearTree;return <article key={name}><h3>{name} 실제 방문</h3><p>{description}</p><strong>현재 상태: {available&&mission?.status==='available'?'도전 가능':mission?.status==='submitted'?'사진 제출 완료':'준비 중'}</strong>{mission?.status==='submitted'?<small>검토 기능은 다음 단계에서 제공됩니다.<br/>{mission.submittedAt?new Date(mission.submittedAt).toLocaleString('ko-KR'):''}</small>:<VisitProofUploader placeId={place} enabled={available&&mission?.status==='available'}/>}</article>})}</section></div>}
function VisitProofUploader({placeId,enabled}:{placeId:'garden'|'bearTree';enabled:boolean}){const [file,setFile]=useState<File>();const [preview,setPreview]=useState<string>();const [pending,setPending]=useState(false);const [message,setMessage]=useState('');useEffect(()=>()=>{if(preview)URL.revokeObjectURL(preview)},[preview]);const choose=(next:File|undefined)=>{if(preview)URL.revokeObjectURL(preview);setFile(next);setPreview(next?URL.createObjectURL(next):undefined);setMessage('')};const submit=async()=>{if(!file){setMessage('제출할 사진을 선택해 주세요.');return}if(!['image/jpeg','image/png','image/webp'].includes(file.type)){setMessage('이미지 파일만 등록할 수 있습니다.');return}if(file.size>10*1024*1024){setMessage('사진 크기는 10MB 이하여야 합니다.');return}setPending(true);setMessage('사진을 제출하는 중입니다.');try{await uploadVisitProof(placeId,file);setMessage('사진 제출 완료')}catch{setMessage('사진 제출에 실패했습니다. 잠시 후 다시 시도해 주세요.')}finally{setPending(false)}};return <div className="visit-proof-uploader"><small>{enabled?'방문 사진을 한 장 등록해 주세요.':'자연 체험을 완료한 후 이용할 수 있습니다.'}</small>{enabled&&<><input type="file" accept="image/jpeg,image/png,image/webp" onChange={event=>choose(event.target.files?.[0])}/>{preview&&<img src={preview} alt="제출할 방문 사진 미리보기"/>}<button type="button" disabled={pending||!file} onClick={()=>void submit()}>{pending?'사진을 제출하는 중입니다.':'방문 사진 제출'}</button></>}{message&&<small>{message}</small>}</div>}
function FlowerCard({flower}:{flower:FlowerProfileCard}){return <article className="memory-tree-flower-card"><header><h3>{flower.displayName}</h3><strong>{flower.interestScore.toFixed(1)}점</strong></header><p>{flower.meaning}</p><small>{flower.description}</small><dl><div><dt>정보창</dt><dd>{flower.infoViewCount}회 · {formatFlowerSeconds(flower.totalInfoViewSeconds)}</dd></div><div><dt>주변 체류</dt><dd>{formatFlowerSeconds(flower.totalNearbySeconds)}</dd></div><div><dt>재방문</dt><dd>{flower.revisitCount}회</dd></div></dl></article>}
