import fs from 'node:fs';
import path from 'node:path';
import type { DirectMessage,DirectRecommendationPlace,DirectRoom,GroupRoom,LakeDailyStats,LakeExperienceId,LakeExperiencePosition,LakeWish,PlayerState,PortalPosition,RespawnPosition,WorldInteractionPosition } from '../../../shared/socket-events.js';
export class RoomStore {
 players=new Map<string,PlayerState>(); groups=new Map<string,GroupRoom>(); pendingDirect=new Map<string,{fromId:string;toId:string}>(); directRooms=new Map<string,DirectRoom>(); directMessages=new Map<string,DirectMessage[]>(); recommendationCache=new Map<string,{roomId:string;places:DirectRecommendationPlace[];expiresAt:number}>(); blockedPairs=new Set<string>();
 portalPositions=new Map<PortalPosition['destination'],PortalPosition>([['bear-tree-park',{destination:'bear-tree-park',x:2122,z:944}],['town',{destination:'town',x:1200,z:1660}],['garden',{destination:'garden',x:682,z:735}],['campus',{destination:'campus',x:2000,z:1180}]]);
 interactionPositions=new Map<WorldInteractionPosition['destination'],WorldInteractionPosition>([['bear-play-zone',{destination:'bear-play-zone',x:1616,z:601}],['bear-tree-park',{destination:'bear-tree-park',x:1200,z:1650}]]);
 lakeExperiencePositions=new Map<LakeExperienceId,LakeExperiencePosition>([['central-plaza',{experience:'central-plaza',x:1150,z:950}],['wind-hill',{experience:'wind-hill',x:350,z:400}]]);
 respawnPosition:RespawnPosition={x:1870,z:1180,yaw:2.1};
 lakeWishes:LakeWish[]=[];
 private dailyDate='';private dailyVisitors=new Set<string>();private dailyExperienceVisits:Record<LakeExperienceId,Set<string>>={'central-plaza':new Set(),'wind-hill':new Set()};
 private portalPositionFile=path.resolve(process.cwd(),'portal-positions.json');
 private interactionPositionFile=path.resolve(process.cwd(),'interaction-positions.json');
 private lakeExperiencePositionFile=path.resolve(process.cwd(),'lake-experience-positions.json');
 private lakeWishFile=path.resolve(process.cwd(),'lake-wishes.json');
 private respawnPositionFile=path.resolve(process.cwd(),'respawn-position.json');
 constructor(){try{const saved=JSON.parse(fs.readFileSync(this.portalPositionFile,'utf8')) as PortalPosition[];saved.forEach(position=>this.setPortalPosition(position,false))}catch{/* The shared defaults are used until a position is saved. */}try{const saved=JSON.parse(fs.readFileSync(this.interactionPositionFile,'utf8')) as WorldInteractionPosition[];saved.forEach(position=>this.setInteractionPosition(position,false))}catch{/* The shared defaults are used until a position is saved. */}try{const saved=JSON.parse(fs.readFileSync(this.lakeExperiencePositionFile,'utf8')) as LakeExperiencePosition[];saved.forEach(position=>this.setLakeExperiencePosition(position,false))}catch{/* The shared defaults are used until a position is saved. */}try{const saved=JSON.parse(fs.readFileSync(this.lakeWishFile,'utf8')) as LakeWish[];this.lakeWishes=saved.filter(wish=>wish&&typeof wish.message==='string'&&typeof wish.nickname==='string').slice(-80)}catch{/* Wishes begin empty on a new server. */}try{this.setRespawnPosition(JSON.parse(fs.readFileSync(this.respawnPositionFile,'utf8')) as RespawnPosition,false)}catch{/* The shared default is used until the previous browser position is migrated. */}}
 setRespawnPosition(position:RespawnPosition,persist=true){if(!Number.isFinite(position.x)||!Number.isFinite(position.z)||!Number.isFinite(position.yaw)||position.x<0||position.x>2400||position.z<0||position.z>1900)return false;this.respawnPosition={x:Math.round(position.x),z:Math.round(position.z),yaw:position.yaw};if(persist)try{fs.writeFileSync(this.respawnPositionFile,JSON.stringify(this.respawnPosition,null,2))}catch(error){console.error('[respawn position persistence failed]',error)}return true}
 allPortalPositions(){return [...this.portalPositions.values()]}
 setPortalPosition(position:PortalPosition,persist=true){if((persist&&position.destination==='garden')||!['town','bear-tree-park','garden','campus'].includes(position.destination)||!Number.isFinite(position.x)||!Number.isFinite(position.z)||position.x<0||position.x>2400||position.z<0||position.z>1900)return false;const saved={destination:position.destination,x:Math.round(position.x),z:Math.round(position.z)};this.portalPositions.set(saved.destination,saved);if(persist)try{fs.writeFileSync(this.portalPositionFile,JSON.stringify(this.allPortalPositions(),null,2))}catch(error){console.error('[portal position persistence failed]',error)}return true}
 allInteractionPositions(){return [...this.interactionPositions.values()]}
 setInteractionPosition(position:WorldInteractionPosition,persist=true){if((persist&&position.destination==='bear-play-zone')||!['bear-tree-park','bear-play-zone'].includes(position.destination)||!Number.isFinite(position.x)||!Number.isFinite(position.z)||position.x<0||position.x>2400||position.z<0||position.z>1900)return false;const saved={destination:position.destination,x:Math.round(position.x),z:Math.round(position.z)};this.interactionPositions.set(saved.destination,saved);if(persist)try{fs.writeFileSync(this.interactionPositionFile,JSON.stringify(this.allInteractionPositions(),null,2))}catch(error){console.error('[interaction position persistence failed]',error)}return true}
 allLakeExperiencePositions(){return [...this.lakeExperiencePositions.values()]}
 setLakeExperiencePosition(position:LakeExperiencePosition,persist=true){if(!['central-plaza','wind-hill'].includes(position.experience)||!Number.isFinite(position.x)||!Number.isFinite(position.z)||position.x<0||position.x>2400||position.z<0||position.z>1900)return false;const saved:LakeExperiencePosition={experience:position.experience,x:Math.round(position.x),z:Math.round(position.z)};this.lakeExperiencePositions.set(saved.experience,saved);if(persist)try{fs.writeFileSync(this.lakeExperiencePositionFile,JSON.stringify(this.allLakeExperiencePositions(),null,2))}catch(error){console.error('[lake experience position persistence failed]',error)}return true}
 addLakeWish(nickname:string,message:string){const wish:LakeWish={id:crypto.randomUUID(),nickname,message,createdAt:Date.now()};this.lakeWishes=[...this.lakeWishes.slice(-79),wish];try{fs.writeFileSync(this.lakeWishFile,JSON.stringify(this.lakeWishes,null,2))}catch(error){console.error('[lake wish persistence failed]',error)}return wish}
 private today(){return new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Seoul',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date())}
 private resetDailyIfNeeded(){const today=this.today();if(today===this.dailyDate)return;this.dailyDate=today;this.dailyVisitors.clear();this.dailyExperienceVisits['central-plaza'].clear();this.dailyExperienceVisits['wind-hill'].clear()}
 recordDailyVisitor(id:string){this.resetDailyIfNeeded();this.dailyVisitors.add(id)}
 recordExperienceVisit(id:string,experience:LakeExperienceId){this.resetDailyIfNeeded();this.dailyExperienceVisits[experience].add(id)}
 lakeDailyStats():LakeDailyStats{this.resetDailyIfNeeded();const centralPlazaVisits=this.dailyExperienceVisits['central-plaza'].size,windHillVisits=this.dailyExperienceVisits['wind-hill'].size;return {date:this.dailyDate,visitors:this.dailyVisitors.size,centralPlazaVisits,windHillVisits,popularExperience:centralPlazaVisits===windHillVisits?'아직 집계 중':centralPlazaVisits>windHillVisits?'중앙광장':'바람의 언덕'}}
 playersIn(mapId:string){return [...this.players.values()].filter(p=>p.mapId===mapId)}
 removePlayer(id:string){this.players.delete(id);for(const group of this.groups.values()){group.memberIds=group.memberIds.filter(x=>x!==id);if(!group.memberIds.length)this.groups.delete(group.id)}for(const [key,req] of this.pendingDirect)if(req.fromId===id||req.toId===id)this.pendingDirect.delete(key)}
 createGroup(owner:PlayerState,name:string,inviteeIds:string[]){const id=`group-${crypto.randomUUID()}`;const group:GroupRoom={id,name:name.trim()||`${owner.nickname}의 모임`,ownerId:owner.id,memberIds:[...new Set([owner.id,...inviteeIds.filter(id=>this.players.has(id))])],mapId:owner.mapId};this.groups.set(id,group);return group}
 pairKey(firstId:string,secondId:string){return [firstId,secondId].sort().join(':')}
 isBlocked(firstId:string,secondId:string){return this.blockedPairs.has(this.pairKey(firstId,secondId))}
 createDirectRoom(first:PlayerState,second:PlayerState){const ids=[first.id,second.id].sort();const existing=[...this.directRooms.values()].find(r=>r.participants.map(p=>p.id).sort().join(':')===ids.join(':'));if(existing){existing.active=true;return existing}const room:DirectRoom={id:`direct-${crypto.randomUUID()}`,participants:[first,second].map(({id,nickname,appearance,matchProfile})=>({id,nickname,appearance,matchProfile})),active:true,acceptedAt:Date.now()};this.directRooms.set(room.id,room);this.directMessages.set(room.id,[]);return room}
 addDirectMessage(message:DirectMessage){const messages=this.directMessages.get(message.directRoomId)??[];messages.push(message);this.directMessages.set(message.directRoomId,messages.slice(-200));return message}
 recentUserMessages(roomId:string,limit=20){return (this.directMessages.get(roomId)??[]).filter(message=>message.type==='user'&&!message.deleted&&message.message.trim()).sort((a,b)=>a.createdAt-b.createdAt).slice(-limit)}
 saveRecommendation(roomId:string,places:DirectRecommendationPlace[]){const recommendationId=crypto.randomUUID();this.recommendationCache.set(recommendationId,{roomId,places,expiresAt:Date.now()+30*60_000});return recommendationId}
 recentRecommendedPlaceIds(roomId:string){const now=Date.now(),ids=new Set<string>();for(const [key,cached] of this.recommendationCache){if(cached.expiresAt<=now){this.recommendationCache.delete(key);continue}if(cached.roomId===roomId)for(const place of cached.places)ids.add(place.id)}return ids}
 getRecommendedPlace(recommendationId:string,roomId:string,placeId:string){const cached=this.recommendationCache.get(recommendationId);if(!cached||cached.roomId!==roomId||cached.expiresAt<=Date.now()){if(cached)this.recommendationCache.delete(recommendationId);return {category:'expired' as const}}const place=cached.places.find(item=>item.id===placeId);return place?{category:'ok' as const,place}:{category:'invalid' as const}}
}
export const roomStore=new RoomStore();
