import Phaser from 'phaser';import { getPart } from '../../data/assetManifest';import type { CharacterParts } from '../../types';
const hex=(c:string)=>Number(c.replace('#','0x'));
export interface AvatarContainer extends Phaser.GameObjects.Container { limbs?:{leftArm:Phaser.GameObjects.Rectangle;rightArm:Phaser.GameObjects.Rectangle;leftLeg:Phaser.GameObjects.Rectangle;rightLeg:Phaser.GameObjects.Rectangle} }
export function createAvatar(scene:Phaser.Scene,x:number,y:number,parts:CharacterParts,name:string,scale=1){
 const root=scene.add.container(x,y) as AvatarContainer;const skin=hex(getPart('face',parts.face).color),top=hex(getPart('top',parts.top).color),bottom=hex(getPart('bottom',parts.bottom).color);
 const shadow=scene.add.ellipse(0,10,38,14,0x192d2a,.22),leftLeg=scene.add.rectangle(-7,1,9,25,bottom).setOrigin(.5,0),rightLeg=scene.add.rectangle(7,1,9,25,bottom).setOrigin(.5,0),body=scene.add.rectangle(0,-20,28,28,top).setStrokeStyle(2,0xffffff,.25),leftArm=scene.add.rectangle(-20,-20,8,29,skin).setOrigin(.5,0),rightArm=scene.add.rectangle(20,-20,8,29,skin).setOrigin(.5,0),face=scene.add.circle(0,-43,13,skin),hair=scene.add.arc(0,-47,14,190,350,false,hex(getPart('hair',parts.hair).color)),eyes=scene.add.text(0,-44,'•  •',{fontSize:'8px',color:'#263238'}).setOrigin(.5),label=scene.add.text(0,-72,name,{fontFamily:'Arial',fontSize:'12px',color:'#173b36',backgroundColor:'#ffffffdd',padding:{x:6,y:3}}).setOrigin(.5);
 root.add([shadow,leftLeg,rightLeg,leftArm,rightArm,body,face,hair,eyes,label]);root.limbs={leftArm,rightArm,leftLeg,rightLeg};root.setScale(scale).setSize(42,78).setInteractive();return root;
}
export function animateAvatar(avatar:AvatarContainer,isMoving:boolean,time:number,direction='down'){if(!avatar.limbs)return;const swing=isMoving?Math.sin(time*.015)*24:0;avatar.limbs.leftArm.setAngle(swing);avatar.limbs.rightArm.setAngle(-swing);avatar.limbs.leftLeg.setAngle(-swing*.55);avatar.limbs.rightLeg.setAngle(swing*.55);avatar.setScale(Math.abs(avatar.scaleX)*(direction==='left'?-1:1),avatar.scaleY);}
